### ISSUE TITLE
2.3.2 release

### ISSUE THREAD

**Issue by chris-allan** [CellProfiler/java#39]
The current version (2.3.1) available on PyPI is broken in a series of ways. A release needs to be made and pushed to PyPI. OMERO compatibility, at a minimum, is out of the box broken at present.

This would not be such a problem except CellProfiler 2.2.x will __NOT__ start up when this version of the dependency is installed. Installation of 2.3.1 is the current behaviour when installing 2.2.x from source. #38 should be merged to restore this compatibility before releasing the current `master`.

/cc @lguerard, @ehrenfeu

**Comment by 0x00b1** [comment]
@chris-allan Thanks, dude. I bumped the version and tagged a release: https://github.com/CellProfiler/prokaryote/releases/tag/2.3.2

The Python wheel is building now and should be uploaded in a few minutes.

**Comment by 0x00b1** [comment]
OK, 2.3.2 is available from PyPI. Would someone mind trying this with OMERO?
